export const Users = [
  {
    id:1,
    profilePicture: "/src/assets/person/pravi.jpeg",
    username: "Pravi",
  },
  {
    id:2,
    profilePicture: "/src/assets/person/yuvarani.jpg",
    username: "Yuvarani",
  },
  {
    id:3,
    profilePicture: "/src/assets/person/sravani.png",
    username: "Sravani",
  },
  {
    id:4,
    profilePicture: "/src/assets/person/yamini.jpg",
    username: "Yamini",
  },
  {
    id:5,
    profilePicture: "/src/assets/person/Naveena.jpg",
    username: "Naveena",
  },
  {
    id:6,
    profilePicture: "/src/assets/person/tejavathi.png",
    username: "Tejavathi",
  },
  {
    id:7,
    profilePicture: "/src/assets/person/bhavana.jpg",
    username: "Bhavana",
  },
  {
    id:8,
    profilePicture: "/src/assets/person/harshitha.jpg",
    username: "Harshitha",
  },
  {
    id:9,
    profilePicture: "/src/assets/person/sushma.jpg",
    username: "Sushma",
  },
  {
    id:10,
    profilePicture: "/src/assets/person/sahiti.jpg",
    username: "Sahiti",
  },
];

export const Questions = [
  {
    id: 1,
    no:1,
    question: "What is the next number in the series 70,54,45,41?",
    date: "2nd Sep 2018",
    userId: 1,
    options: [40, 35, 45, 54],
    answer: 40,
  },
  {
    id: 2,
    no:1,
    question: "A certain sum of money is sufficient to pay either George’s wages for 15 days or mark’s wages for 10 days, for how long will it suffice it both George and mark work together?",
    date: "15 mins ago",
    userId: 2,
    options: [9, 8, 6, 5],
    answer: 6 ,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/src/assets/post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/src/assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/src/assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/src/assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/src/assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/src/assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/src/assets/post/9.png",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/src/assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
